name: workflow1
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      # - name: Set up Node.js 20
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Build image
        run: docker image build -t 9574872248/watchlist .
